### ISSUE TITLE
Process_inputs does not clip Vroads 

### ISSUE THREAD

**Issue by RikLubbers** [unige-geohealth/inAccessMod#9]
**Description**
Currently, when using the `process_inputs` command in the inaccessmod tool, the `Vroads` layer is not clipped to the specified administrative boundaries. This limitation affects the accuracy and relevance of analysis for users working on subnational scales.

**Feature Request**
It would be highly beneficial for the `process_inputs` command to include functionality to clip the `Vroads` layer using the administrative boundaries provided by the user. This feature would greatly enhance the utility of inaccessmod for subnational analysis, ensuring that infrastructure data is accurately represented within the specific areas of interest. 

**Example Use Case**
I am currently working on a project analyzing Kampala, Uganda. The ability to clip the `Vroads` layer to our specific administrative boundaries would mean that I do not have to go outside of my IDE to clip in in QGIS.

Thank you for considering this feature request. Implementing this functionality could improve the applicability of inaccessmod for detailed, location-specific studies.

**Comment by ptimoner** [comment]
Thanks @RikLubbers. Indeed, this is a feature that was not included because 1) for large countries and dense road networks it can be time consuming and 2) the fact that roads and rivers are not clipped has no impact on the accessibility modelling. But, this is something we might add in the new release of the package we are working on (at least as optional feature).

**Comment by RikLubbers** [comment]
Thank you for your reply. I understand your point. The reason I would find it useful is that uploading the countrywide OSM file to accessmod takes a long time so, therefore, the clipping part.
